# Site settings
title: gosha20777
description: Created by gosha20777

url: https://github.com/gosha20777/
baseurl: ""
aboutUrl: /about
paginate_path: "blog/page:num/"
permalink: blog/:title/


navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Search
   url: /search

social:
   github: gosha20777
   vkontakte: gosha20777
#   twitter: brianmaierjr
   facebook: gosha20777
   email: gosha20777@live.ru

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
